["openpilot terms"]

"big model".description = "A new paradigm in model development that takes a bigger input frame. Full frame is 1164x874, little model is a 512x256 crop, big model is a 1024x512 crop, 4x bigger than little. Make box bigger, drive better. Useful for signs and lights."

"Driving Model".abbreviation = "model"
"Driving Model".description = "The resulting neural network after Comma trains on driving data on their supercomputer.  This file lives on the device, and processes inputs to give outputs relevant to driving. Usually takes the form of an ONNX file, or a THNEED file after compilation on device. This file does not change or get trained on device, only processes inputs and outputs. See [the list of driving models](https://github.com/commaai/openpilot/wiki/Driving-Models) for names and details of models over time."

"End to end".abbreviation = "e2e"
"End to end".description = "End to end means the model reacts like a human would. It assesses the whole picture and acts accordingly. Unlike other approaches where things must be labeled by hand, end to end learns all the nuances of driving. A model is basically trained on what human drivers would do in a certain situation and attempts to reproduce that behavior."

longitudinal.abbreviation = "long"
longitudinal.description = "Refers to gas and brake control."

lateral.abbreviation = "lat"
lateral.description = "Refers to steering control."

"Model predictive control".abbreviation = "mpc"
"Model predictive control".description = "An advanced method of process control that is used to control a process while satisfying a set of constraints. Used for longitudinal and lateral control."

lead.description = "Selected radar point from your car's radar by the driving model of openpilot using the camera. Used for longitudinal MPC. Usual attributes: distance, speed, and acceleration."


["driver-assistance terms"]

"Adaptive Cruise Control".abbreviation = "ACC"
"Adaptive Cruise Control".description = "A cruise control system that automatically adjusts the vehicle speed to maintain a safe distance from vehicles ahead."

"Advanced Driver-Assistance Systems".abbreviation = "ADAS"
"Advanced Driver-Assistance Systems".description = "Electronic systems that aid the driver."

"(Automatic) Lane Centering".abbreviation = "(A)LC"
"(Automatic) Lane Centering".description = "A system designed to keep a car centered in the lane, relieving the driver of the task of steering."

"Collision Avoidance System".abbreviation = "AEB, CMS, FCW(S), FCA, PCS"
"Collision Avoidance System".description = "A system designed to prevent or reduce the severity of a collision."

"Driver Monitoring (System)".abbreviation = "DM(S), DAM"
"Driver Monitoring (System)".description = "A system that uses infrared sensors and/or cameras to monitor driver attentiveness."

"Dynamic Range Cruise Control".abbreviation = "DRCC"
"Dynamic Range Cruise Control".description = "A cruise control system that automatically adjusts the vehicle speed to maintain a safe distance from vehicles ahead."

"hugging".description = "An undesired behavior where the vehicle drives too closely to one side of the lane."

"Lane Keep Assist (System)".abbreviation = "LKA(S)"
"Lane Keep Assist (System)".description = "Lane keep assist is what comes with most cars sold today. It will assist the driver if they go over a lane line, but will not keep the car centered in the lane."

"Lane Departure Warning (System)".abbreviation = "LDW(S), LDA"
"Lane Departure Warning (System)".description = "Lane departure warning will beep when a car goes over a lane line."

"Pedestrian Crash Avoidance Mitigation".abbreviation = "PCAM"
"Pedestrian Crash Avoidance Mitigation".description = "A system that uses computer and artificial intelligence technology to recognize pedestrians and bicycles in an automobile's path to take action for safety."

"ping pong".description = "An undesired behavior where the vehicle sways from one side of the lane to the other repeatedly. The desired behavior is to stay in the center of the lane."

"wobble".description = "Similar to ping pong, but where the vehicle drives mostly centered in the lane but sways slightly from side to side. Primarily due to improper tuning of the steering control system, influence from wind, or poor lane/path perception due to rain, dirt, and/or debris on the vehicles windshield."

"Traffic-sign recognition".abbreviation = "TSR"
"Traffic-sign recognition".description = 'A system by which a vehicle is able to recognize the traffic signs put on the road e.g. "speed limit" or "children" or "turn ahead".'

"Stop and Go".abbreviation = "SnG"
"Stop and Go".description = "The ability for the car to be brought to a standstill and then resume driving without needing to disengage or reengage openpilot."

"Vision Only Adaptive Cruise Control".abbreviation = "VOACC"
"Vision Only Adaptive Cruise Control".description = "The exclusive use of cameras instead of radar to provide adaptive cruise control functions."


["automotive terms"]

"Controller Area Network".abbreviation = "CAN, CAN bus"
"Controller Area Network".description = "A message-based protocol that provides a standardized way for ECUs to communicate with each other."

"CAN-FD".description = "A newer version of CAN that supports higher data rates and longer messages. A red panda is required to interface with CAN-FD vehicles."

"Electronic Control Unit".abbreviation = "ECU"
"Electronic Control Unit".description = "Any embedded system in automotive electronics that controls one or more of the electrical systems or subsystems in a vehicle."

"Electric Power Steering".abbreviation = "EPS"
"Electric Power Steering".description = "Uses an electric motor to assist the driver of a vehicle. Sensors detect the position and torque of the steering column, and a computer module applies assistive torque via the motor, which connects to either the steering gear or steering column."

"On-Board Diagnostics Connector".abbreviation = "OBD-II, OBD-II port"
"On-Board Diagnostics Connector".description = "OBD systems give the vehicle owner or repair technician access to the status of the various vehicle sub-systems. The comma power v2 uses this port to provide constant power to the comma two as well as access the diagnostic bus for FW query."

"Full Self Driving".abbreviation = "FSD"
