site_name: openpilot
site_url: https://docs.comma.ai
github_repo: commaai/openpilot
discord_url: https://discord.comma.ai

# TODO automate somehow?
version: 0.9.8

watch:
  - "theme/"

theme:
  name: null
  custom_dir: "theme/"

# TODO use macros to automate version tag?
# plugins:
#   # TODO implement search ?
#   - search
#   - macros

nav:
  - Getting Started:
    - What is openpilot?: getting-started/what-is-openpilot.md
  - How-to:
    - Turn the speed blue: how-to/turn-the-speed-blue.md
    - Connect to a comma 3/3X: how-to/connect-to-comma.md
    #- Replay a drive: how-to/replay-a-drive.md
  - Concepts:
    - Logs: concepts/logs.md
    - Safety: concepts/safety.md
  - Car Porting:
    - What is a car port?: car-porting/what-is-a-car-port.md
    - Porting a car brand: car-porting/brand-port.md
    - Porting a car model: car-porting/model-port.md
  - Contributing:
    - Roadmap: contributing/roadmap.md
    #- Architecture: contributing/architecture.md
    - Contributing Guide →: https://github.com/commaai/openpilot/blob/master/docs/CONTRIBUTING.md
  - Links:
    - Blog →: https://blog.comma.ai
    - Bounties →: https://comma.ai/bounties
    - GitHub →: https://github.com/commaai
    - Discord →: https://discord.comma.ai
    - X →: https://x.com/comma_ai
